name: 'dsci-575-project'
channels:
  - conda-forge
dependencies:
  - ipykernel
  - torchvision
  - scikit-learn=1.7.1
  - nb_conda_kernels
  - pandas
  - python=3.12
  - ipywidgets
  - pip
  - sentence-transformers
  - requests
  - pytorch
  - streamlit
  - python-dotenv
  - huggingface_hub
  - transformers
  - pip:
      - langchain-core
      - langchain-community
      - rank_bm25
      - faiss-cpu
      - langchain-huggingface